using System;
using System.Collections.Generic;
using System.Text;

namespace OSMtoSharp
{
    public enum BuildingsTypeEnum
    {
        [Enum("apartments")]
        Apartments,
        [Enum("farm")]
        Farm,
        [Enum("hotel")]
        Hotel,
        [Enum("house")]
        House,
        [Enum("detached")]
        Detached,
        [Enum("residential")]
        Residential,
        [Enum("dormitory")]
        Dormitory,
        [Enum("terrace")]
        Terrace,
        [Enum("houseboat")]
        Houseboat,
        [Enum("bungalow")]
        Bungalow,
        [Enum("static_caravan")]
        Static_caravan,
        [Enum("commercial")]
        Commercial,
        [Enum("office")]
        Office,
        [Enum("industrial")]
        Industrial,
        [Enum("retail")]
        Retail,
        [Enum("warehouse")]
        Warehouse,
        [Enum("bakehouse")]
        Bakehouse,
        [Enum("cathedral")]
        Cathedral,
        [Enum("chapel")]
        Chapel,
        [Enum("church")]
        Church,
        [Enum("mosque")]
        Mosque,
        [Enum("temple")]
        Temple,
        [Enum("synagogue")]
        Synagogue,
        [Enum("shrine")]
        Shrine,
        [Enum("civic")]
        Civic,
        [Enum("hospital")]
        Hospital,
        [Enum("school")]
        School,
        [Enum("stadium")]
        Stadium,
        [Enum("train_station")]
        Train_station,
        [Enum("transportation")]
        Transportation,
        [Enum("university")]
        University,
        [Enum("public")]
        Public,
        [Enum("barn")]
        Barn,
        [Enum("bridge")]
        Bridge,
        [Enum("bunker")]
        Bunker,
        [Enum("cabin")]
        Cabin,
        [Enum("construction")]
        Construction,
        [Enum("cowshed")]
        Cowshed,
        [Enum("digester")]
        Digester,
        [Enum("farm_auxiliary")]
        Farm_auxiliary,
        [Enum("garage")]
        Garage,
        [Enum("garages")]
        Garages,
        [Enum("greenhouse")]
        Greenhouse,
        [Enum("hangar")]
        Hangar,
        [Enum("hut")]
        Hut,
        [Enum("roof")]
        Roof,
        [Enum("shed")]
        Shed,
        [Enum("stable")]
        Stable,
        [Enum("sty")]
        Sty,
        [Enum("transformer_tower")]
        Transformer_tower,
        [Enum("service")]
        Service,
        [Enum("kiosk")]
        Kiosk,
        [Enum("carport")]
        Carport,
        [Enum("ruins")]
        Ruins,
        [Enum("yes")]
        Yes,
        [Enum("user defined")]
        User_defined

    }
}
